---
# Each entry in this file is a label that will be applied to pull requests
# if there is a match based on the matching rules for the entry. Please see
# the actions/labeler documentation for more information:
# https://github.com/actions/labeler#match-object
#
# Note: Verify that the label you want to use is defined in the
# crazy-max/ghaction-github-labeler configuration file located at
# .github/labels.yml.

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          # Add any dependency files used.
          - "**/package-lock.json"
          - "**/package.json"
          - .pre-commit-config.yaml
docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/compose*.yml"
          - "**/docker-compose*.yml"
          - "**/Dockerfile*"
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
javascript:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.js"
          - "**/*.jsx"

shell script:
  - changed-files:
      - any-glob-to-any-file:
          # If this project has any shell scripts that do not end in the ".sh"
          # extension, add them below.
          - "**/*.sh"
          - bump-version
          - setup-env

test:
  - changed-files:
      - any-glob-to-any-file:
          # Add any test-related files or paths.
          - .mdl_config.yaml
          - .yamllint
          - docker-compose.yml
          - tests/**
typescript:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.ts"
          - "**/*.tsx"
upstream update:
  - head-branch:
      # Any Lineage pull requests should use this branch.
      - lineage/skeleton
version bump:
  - changed-files:
      - any-glob-to-any-file:
          # Ensure this matches your version tracking file(s).
          - src/version.txt
